// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/python/index.en-US":{"path":"en-US/python","id":"docs/python/index.en-US","parentId":"DocLayout"},"docs/python/index":{"path":"python","id":"docs/python/index","parentId":"DocLayout"},"docs/index.en-US":{"path":"en-US/","id":"docs/index.en-US","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout","prerender":false}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'D:/codebox/pythonspace/awesome-python/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp-production__dumi__theme__ContextWrapper" */'D:/codebox/pythonspace/awesome-python/.dumi/tmp-production/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'D:/codebox/pythonspace/awesome-python/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/python/index.en-US': React.lazy(() => import(/* webpackChunkName: "docs__python__index.en-US.md" */'D:/codebox/pythonspace/awesome-python/docs/python/index.en-US.md')),
'docs/python/index': React.lazy(() => import(/* webpackChunkName: "docs__python__index.md" */'D:/codebox/pythonspace/awesome-python/docs/python/index.md')),
'docs/index.en-US': React.lazy(() => import(/* webpackChunkName: "docs__index.en-US.md" */'D:/codebox/pythonspace/awesome-python/docs/index.en-US.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'D:/codebox/pythonspace/awesome-python/docs/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'D:/codebox/pythonspace/awesome-python/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
