// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'D:/codebox/pythonspace/awesome-python/node_modules/dumi/theme-default/slots/Hero/index.js';
