name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Configure Git
      run: |
        git config user.email "actionbot"
        git config user.name "andybuibui"
    - name: install
      run: |
        npm install
    - name: Build
      run: |
        npm run build    
    - name: deploy
      run: |
        npm run deploy
    env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
